config/routes.rb
Rails.application.routes.draw do
  resources :discards
  resources :cards
  resources :card_requests
  resources :militaries
  resources :hierarchies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'militaries#index'

  get 'create_card_request', to: 'card_requests#create', as: :create_card_request
  get 'print_request', to: 'cards#create', as: :print_request
  get 'cancel_card_request(.:id)', to:'card_requests#cancel', as: :cancel_card_request
  patch 'giving_card', to:'cards#giving', as: :giving_card
  patch 'returning_card', to:'cards#returning', as: :returning_card

  #Print one card
  post 'print_a_card', to: 'cards#print_a_card', as: :print_a_card
  #Print 4 first cards
  get 'print_cards', to: 'cards#print_cards', as: :print_cards
  post 'create_cards', to: 'cards#create_cards', as: :create_cards

end

app/models/discard.rb
# Classe responsavel por representar Discartes
class Discard < ApplicationRecord
  belongs_to :card_request

  # Validacoes
  validates :card_number, presence: true, uniqueness: true

  def fill_by_request(object_request_id)
    card_request = CardRequest.find(object_request_id)
    card = Card.find_by_registration(card_request.military_registration)
    self.card_request = card_request
    self.card_number = card.card_number
  end

  def document_request_reference
    card_request.document_reference
  end

  def card_request_id
    card_request.id
  end

  # return Registration and Name
  def register_and_name
    card_request = CardRequest.find_by_id(card_request_id)
    military = Military.find_by_registration(card_request.military_registration)
    military.register_and_name
  end

end

app/controllers/discards_controller.rb
class DiscardsController < ApplicationController
  before_action :set_discard, only: %i[show edit update destroy]

  # GET /discards
  # GET /discards.json
  def index
    @q = Discard.ransack(params[:q])
    @discards = @q.result(distinct: true).joins(:card_request).order(created_at: :asc)
  end

  # GET /discards/1
  # GET /discards/1.json
  def show; end

  # GET /discards/new
  def new
    @discard = Discard.new
    card_request_id = params[:card_request_id]
    abort params[:card_request_id].inspect
    @discard.fill_by_request(card_request_id)
  end

  # GET /discards/1/edit
  def edit; end

  # POST /discards
  # POST /discards.json
  def create
    ActiveRecord::Base.transaction do
      @discard = Discard.new(discard_params)
      card = CardsHelper.find_to_discard(@discard.card_request_id)
      if CardsHelper.validate_card_number_by_card(@discard.card_number)
        redirect_to cards_url, flash: { error: StrHelper.system_i18n_upper(:card_number_exist, %i[errors messages]) }
      elsif @discard.save
        if Card.destroy(card.id)
          redirect_to discards_url, flash: { success: StrHelper.system_i18n_upper(:create, %i[activerecord success]) }
        else
          raise ActiveRecord::Rollback
          redirect_to cards_url, flash: { error: discard.errors.full_messages.first }
        end
      else
        redirect_to cards_url, flash: { error: @discard.errors.full_messages.first }
      end
    end
  end

  # PATCH/PUT /discards/1
  # PATCH/PUT /discards/1.json
  def update
    if @discard.update(discard_params)
      redirect_to @discard, flash: { success: StrHelper.system_i18n_upper(:update, %i[activerecord success]) }
    else
      redirect_to cards_url, flash: { error: discard.errors.full_messages.first }
    end
  end

  # DELETE /discards/1
  # DELETE /discards/1.json
  def destroy
    if @discard.destroy
      redirect_to discards_url, flash: { success: StrHelper.system_i18n_upper(:destroy, %i[activerecord success]) }
    else
      redirect_to discards_url, flash: { error: @discard.errors.full_messages.first }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_discard
    @discard = Discard.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def discard_params
    params.require(:discard).permit(:card_number, :card_request_id, :reason_discard)
  end
end

app/helpers/discards_helper.rb
module DiscardsHelper

    def self.validate_card_number_by_discard(card_number)
        Discard.find_by_card_number(card_number).present?
    end
    
end

app/views/discards/_form.html.erb
<div class="box box-info">
    <%= form_with(model: discard, local: true, class: 'form-horizontal') do |form| %>
      <div class="box-body">
        <div class="form-group">
            <%= form.label( :card_number, StrHelper.attribute_i18n_upper(:card_number, [:card]), class: 'col-sm-5 control-label') %>
            <div class="col-sm-6">
                <%= form.text_field( :card_number, id: :discard_card_number, class: "form-control", readonly: true) %>
            </div>
        </div>

        <%= form.hidden_field(:card_request_id, value: discard.card_request_id) %>
        <div class="form-group">
            <%= label_tag( :document_request_reference, StrHelper.attribute_i18n_upper(:document_reference, [:card_request]), class: 'col-sm-5 control-label') %>
            <div class="col-sm-6">
                <%= text_field_tag(:document_request_reference, discard.document_request_reference, class: "form-control", disabled: true)%>
            </div>
        </div>

        <div class="form-group">
            <%= form.label( :reason_discard, StrHelper.attribute_i18n_upper(:reason_discard, [:discard]), class: 'col-sm-5 control-label') %>
            <div class="col-sm-6">
                <%= form.text_area( :reason_discard, id: :discard_reason_discard, class: "form-control" )%>
            </div>
        </div>
        <div class="actions">
          <%= link_to(StrHelper.system_i18n(:back, [:helpers, :layouts]), discards_path, class:"btn btn-default btn-sm") %>
          <div class="box-tools pull-right">
            <%= form.submit( StrHelper.system_i18n(:save, [:helpers, :layouts]), class:"btn btn-success btn-sm" )%>
          </div>
        </div>
      </div>    
    <% end %>
  </div>

app/views/discards/edit.html.erb
<h3><%= StrHelper.system_i18n(:edit, [:helpers, :layouts]) %> <%= StrHelper.model_i18n(:one, [:discard])%></h3>

<%= render 'form', discard: @discard %>

app/views/discards/index.html.erb
<h3>
    <%= StrHelper.model_i18n(:other, [:discard])%>
  </h3>
  <p id="notice">
    <%= notice %>
  </p>
  <div class="box">
    <div class="box-body">
      <%= search_form_for @q, html: {class: "form-horizontal", role: "search"} do |f| %>
        <%= f.search_field :card_number_or_card_request_id_or_reason_discard_cont, class: "form-control", placeholder: StrHelper.system_i18n(:search, [:helpers, :layouts]) %>
      <% end %>
      <table class="table table-responsive table-hover">
        <thead>
          <tr>
            <th class="col-sm-3 text-center"><%= sort_link(@q, :card_request, StrHelper.attribute_i18n_upper(:registration_name, [:military])) %></th>
            <th class="col-sm-3 text-center"><%= sort_link(@q, :card_request, StrHelper.attribute_i18n_upper(:document_reference, [:card_request])) %></th>
            <th class="col-sm-2 text-center"><%= sort_link(@q, :card_number, StrHelper.attribute_i18n_upper(:card_number, [:card])) %></th>
            <th class="col-sm-3 text-center"><%= sort_link(@q, :reason_discard, StrHelper.attribute_i18n_upper(:reason_discard, [:discard])) %></th>          
            <th class="col-sm-2 text-center"><%= StrHelper.system_i18n_upper(:action, [:helpers, :layouts]) %></th>
          </tr>
        </thead>
        <tbody>
          <% @discards.each do |discard| %>
            <tr>
              <td align="center">
                <%= discard.register_and_name %>
              </td>
              <td align="center">
                <%= discard.document_request_reference %>
              </td>
              <td align="center">
                <%= discard.card_number %>
              </td>
              <td align="center">
                <%= discard.reason_discard %>
              </td>
              <td align="center">
                <%= hidden_field(@discard, discard) %>
                <%= link_to( "", edit_discard_path(discard.id), class: 'btn btn-info btn-xs fa fa-edit', title: StrHelper.system_i18n(:edit, [:helpers, :layouts]), 'data-toggle' => 'tooltip', 'data-placement' => 'left')%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  

app/views/discards/new.html.erb
<h3><%= StrHelper.system_i18n(:new, [:helpers, :layouts]) %> <%= StrHelper.model_i18n(:one, [:discard])%></h3>

<%= render 'form', discard: @discard %>

app/views/discards/show.html.erb
<h3><%= StrHelper.system_i18n(:show, [:helpers, :layouts]) %> <%= StrHelper.model_i18n(:one, [:discard])%></h3>
<p id="notice"><%= notice %></p>
<div class="box box-info">  
  <div class="form-horizontal">
    <div class="box-body">
      <div class="form-group">
        <%= label_tag( :card_number, StrHelper.attribute_i18n_upper(:card_number, [:card]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:card_number, @discard.card_number, {class: "form-control", disabled: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :document_request_reference, StrHelper.attribute_i18n_upper(:document_reference, [:card_request]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag( :document_request_reference, @discard.document_request_reference, {class: "form-control", disabled: true}) %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :reason_discard, StrHelper.attribute_i18n_upper(:reason_discard, [:discard]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_area_tag( :reason_discard, @discard.reason_discard, {class: "form-control", disabled: true}) %>
        </div>
      </div>
      <div class="actions">        
        <%= link_to(StrHelper.system_i18n(:back, [:helpers, :layouts]), hierarchies_path, class:"btn btn-default btn-sm") %>
        <div class="box-tools pull-right">
            <%= link_to(StrHelper.system_i18n(:edit, [:helpers, :layouts]), edit_discard_path(@discard), class:"btn btn-info btn-sm") %>
        </div>                
      </div>
    </div>
  </div>
</div>