config/routes.rb
Rails.application.routes.draw do
  resources :discards
  resources :cards
  resources :card_requests
  resources :militaries
  resources :hierarchies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'militaries#index'

  get 'create_card_request', to: 'card_requests#create', as: :create_card_request
  get 'print_request', to: 'cards#create', as: :print_request
  get 'cancel_card_request(.:id)', to:'card_requests#cancel', as: :cancel_card_request
  patch 'giving_card', to:'cards#giving', as: :giving_card
  patch 'returning_card', to:'cards#returning', as: :returning_card

  #Print one card
  post 'print_a_card', to: 'cards#print_a_card', as: :print_a_card
  #Print 4 first cards
  get 'print_cards', to: 'cards#print_cards', as: :print_cards
  post 'create_cards', to: 'cards#create_cards', as: :create_cards

end

app/models/military.rb
# Classe responsavel por representar Militar
class Military < ApplicationRecord
  
  before_validation :clean_mask, :uppercase_strings

  # Validacoes
  validates :name, presence: true, length: { minimum: 3 }
  validates :cpf, presence: true, uniqueness: true, length: { is: 11 }
  validates :identification, presence: true, length: { is: 8 }
  validates :father_name, length: { minimum: 3 }
  validates :mother_name, length: { minimum: 3 }
  validates :born_date, presence: true
  validates :registration, presence: true, length: { is: 7 }
  validates :naturalness, presence: true, length: { minimum: 3 }
  validates :vote_number, presence: true, length: { is: 12 }
  validates :vote_zone, presence: true, length: { is: 3 }
  validates :vote_section, presence: true, length: { is: 3 }
  validates :digital_factor, presence: true, length: { is: 10 }
  validates :blood_type, presence: true
  validates :blood_factor, presence: true

  belongs_to :hierarchy

  enum blood_type: { undefine_type: 0, a: 1, b: 2, ab: 3, o: 4 }
  enum blood_factor: { undefine_factor: 0, positive: 1, negative: 2 }

  def fill_default
    self.carry_weapon = :true
  end

  # Tornar todas strings upercase
  def uppercase_strings
    self.name = StrHelper.str_upper(self.name)
    self.father_name = StrHelper.str_upper(self.father_name)
    self.mother_name = StrHelper.str_upper(self.mother_name)
    self.naturalness = StrHelper.str_upper(self.naturalness)
  end

  def clean_mask
    cpf.gsub!(/[^0123456789]/, '')
    identification.gsub!(/[^0123456789]/, '')
    registration.gsub!(/[^0123456789]/, '')
    vote_number.gsub!(/[^0123456789]/, '')
    vote_zone.gsub!(/[^0123456789]/, '')
    vote_section.gsub!(/[^0123456789]/, '')
    digital_factor.gsub!(/[^a-zA-Z0-9]/, '')
  end

  def register_and_name
    "#{registration} - #{name}"
  end

  def hierarchy_register_and_name
    "#{hierarchy_name} - #{registration} - #{name}"
  end  

  def hierarchy_name
    self.hierarchy.name
  end

  def hierarchy_acronym
    self.hierarchy.acronym
  end

  # Formatacao de data para exibicao
  def date_formatted
    self.born_date.strftime('%d/%m/%Y') if born_date?
  end

  # Internationalization (I18n)
  # blood_type: Internationalization (I18n)
  def i18n_blood_type
    StrHelper.attribute_i18n(blood_type.to_sym, %i[military blood_types])
  end

  # blood_type: Internationalization (I18n)
  def i18n_upper_blood_type
    StrHelper.attribute_i18n_upper(blood_type.to_sym, %i[military blood_types])
  end

  # Hash blood_types: Internationalization (I18n)
  def self.i18n_blood_types(hash = {})
    blood_types.each_key do |key|
      hash[StrHelper.attribute_i18n(key.to_sym, %i[military blood_types])] = key
    end
    hash
  end

  # Hash blood_types: Internationalization (I18n) with uppercase
  def self.i18n_upper_blood_types(hash = {})
    blood_types.each_key do |key|
      hash[StrHelper.attribute_i18n_upper(key.to_sym, %i[military blood_types])] = key
    end
    hash
  end

  # blood_type: Internationalization (I18n)
  def i18n_blood_factor
    StrHelper.attribute_i18n(blood_factor.to_sym, %i[military blood_factors])
  end

  # blood_factor: Internationalization (I18n) with uppercase
  def i18n_upper_blood_factor
    StrHelper.attribute_i18n_upper(blood_factor.to_sym, %i[military blood_factors])
  end

  # Hash blood_factors: Internationalization (I18n)
  def self.i18n_blood_factors(hash = {})
    blood_factors.each_key do |key|
      hash[StrHelper.attribute_i18n(key.to_sym, %i[military blood_factors])] = key
    end
    hash
  end

  # Hash blood_factors: Internationalization (I18n) with uppercase
  def self.i18n_upper_blood_factors(hash = {})
    blood_factors.each_key do |key|
      hash[StrHelper.attribute_i18n_upper(key.to_sym, %i[military blood_factors])] = key
    end
    hash
  end
end

app/controllers/militaries_controller.rb
# Classe controla funcoes referentes aos militares
class MilitariesController < ApplicationController
  before_action :set_military, only: %i[show edit update destroy]

  # GET /militaries
  # GET /militaries.json
  def index
    @q = Military.ransack(params[:q])
    @militaries = @q.result(distinct: true).order(name: :asc)
  end

  # GET /militaries/1
  # GET /militaries/1.json
  def show; end

  # GET /militaries/new
  def new
    @military = Military.new
    @military.fill_default
  end

  # GET /militaries/1/edit
  def edit; end

  # POST /militaries
  # POST /militaries.json
  def create
    @military = Military.new(military_params)
    if @military.save
      redirect_to @military, flash: { success: StrHelper.system_i18n_upper(:create,[:activerecord, :success]) }
    else
      flash.now[:error] = @military.errors.full_messages.first
      render :new
    end
  end

  # PATCH/PUT /militaries/1
  # PATCH/PUT /militaries/1.json
  def update
    if @military.update(military_params)
      redirect_to @military, flash: { success: StrHelper.system_i18n_upper(:update,[:activerecord, :success]) }
    else
      flash.now[:error] = @military.errors.full_messages.first
      render :edit
    end
  end

  # DELETE /militaries/1
  # DELETE /militaries/1.json
  def destroy
    if @military.destroy
      redirect_to militaries_url, flash: { success: StrHelper.system_i18n_upper(:destroy,[:activerecord, :success]) }
    else
      redirect_to militaries_url, flash: { error: @military.errors.full_messages.first }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_military
    @military = Military.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def military_params
    params.require(:military).permit(:name, :identification, :hierarchy_id, :father_name, :mother_name, :born_date, :registration, :naturalness, :vote_number, :vote_zone, :vote_section, :cpf, :digital_factor, :blood_type, :blood_factor, :carry_weapon)
  end
end

app/helpers/militaries_helper.rb
module MilitariesHelper
  # return Registration and Name
  def self.hierarchy_register_and_name(registration)
    military = Military.find_by_registration(registration)
    military.hierarchy_register_and_name
  end
  # return Registration and Name
  def self.military_name(registration)
    military = Military.find_by_registration(registration)
    military.name
  end

  def self.fit_carry_weapon(fit)
    case fit
    when true
      StrHelper.system_i18n_upper(:fit, %i[helpers select])
    when false
      StrHelper.system_i18n_upper(:unfit, %i[helpers select])
    end
  end
end

app/views/militaries/_form.html.erb
<div class="box box-info">
  <%= form_with(model: military, local: true, class: 'form-horizontal') do |form| %>
    <div class="box-body">
      <div class="form-group">
        <%= form.label(:name, StrHelper.attribute_i18n_upper(:name, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.text_field( :name, id: :military_name, class: "form-control") %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label( :cpf, StrHelper.attribute_i18n_upper(:cpf, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.text_field :cpf, id: :military_cpf, data:{ inputmask:'"mask": "999.999.999-99"', mask:""}, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label(:identification, StrHelper.attribute_i18n_upper(:identification, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.text_field :identification, id: :military_identification, data:{ inputmask:'"mask": "9999999-9"', mask:""}, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label(:hierarchy, StrHelper.model_i18n_upper(:one, [:hierarchy]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.select(:hierarchy_id, Hierarchy.all.order(:rank).map {|hierarchy| [hierarchy.name, hierarchy.id]}, {}, {class: "form-control"}) %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label(:father_name, StrHelper.attribute_i18n_upper(:father_name, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.text_field :father_name, id: :military_father_name, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label(:mother_name, StrHelper.attribute_i18n_upper(:mother_name, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.text_field :mother_name, id: :military_mother_name, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label( :born_date, StrHelper.attribute_i18n_upper(:born_date, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <div class="input-group date">
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
              <%= form.text_field :born_date, id: :military_born_date, type: "date", class: "form-control pull-right" %>
            </div>
          </div>
      </div>
      <div class="form-group">
        <%= form.label( :registration, StrHelper.attribute_i18n_upper(:registration, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.text_field :registration, id: :military_registration, data:{ inputmask:'"mask": "999999-9"', mask:""}, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label( :naturalness, StrHelper.attribute_i18n_upper(:naturalness, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.select(:naturalness, City.all.order(:name).map {|city| [city.city_and_state, city.city_and_state]}, {}, {class: "form-control"}) %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label( :vote_number, StrHelper.attribute_i18n_upper(:vote_number, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.text_field :vote_number, id: :military_vote_number, data:{ inputmask:'"mask": "999999999999"', mask:""}, class: "form-control" %>            
          </div>
      </div>

      <div class="form-group">
        <%= form.label( :vote_zone, StrHelper.attribute_i18n_upper(:vote_zone, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.text_field :vote_zone, id: :military_vote_zone, data:{ inputmask:'"mask": "999"', mask:""}, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label( :vote_section, StrHelper.attribute_i18n_upper(:vote_section, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.text_field :vote_section, id: :military_vote_section, data:{ inputmask:'"mask": "999"', mask:""}, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label( :digital_factor, StrHelper.attribute_i18n_upper(:digital_factor, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.text_field :digital_factor, id: :military_digital_factor, data:{ inputmask:'"mask": "A-9999/A-9999"', mask:""}, class: "form-control" %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label( :blood_type, StrHelper.attribute_i18n_upper(:blood_type, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.select(:blood_type, options_for_select(Military.i18n_upper_blood_types, @military.blood_type), {}, {class: "form-control"}) %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label( :blood_factor,StrHelper.attribute_i18n_upper(:blood_factor, [:military]), class: 'col-sm-2 control-label') %>
          <div class="col-sm-6">
            <%= form.select(:blood_factor, options_for_select(Military.i18n_upper_blood_factors, @military.blood_factor), {}, {class: "form-control"}) %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label( :carry_weapon, StrHelper.attribute_i18n_upper(:carry_weapon, [:military]), class: 'col-sm-2 control-label') %>                  
        <div class="col-sm-6">
          <%= form.radio_button( :carry_weapon, true, id: :military_carry_weapon, class: "col-sm-1") %>  
          <%= form.label( :carry_weapon, StrHelper.system_i18n(:fit, [:helpers, :select]), class: "col-sm-3")  %>
          <%= form.radio_button( :carry_weapon, false, id: :military_carry_weapon, class: "col-sm-1") %>  
          <%= form.label( :carry_weapon, StrHelper.system_i18n(:unfit, [:helpers, :select]), class: "col-sm-3")  %>
        </div>          
      </div>
      
      <div class="actions">
        <%= link_to(StrHelper.system_i18n(:back, [:helpers, :layouts]), militaries_path, class:"btn btn-default btn-sm") %>
        <div class="box-tools pull-right">
          <%= form.submit( StrHelper.system_i18n(:save, [:helpers, :layouts]), class:"btn btn-success btn-sm" )%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/militaries/edit.html.erb
<h3><%= StrHelper.system_i18n(:edit, [:helpers, :layouts]) %> <%= StrHelper.model_i18n(:one, [:military])%></h3>

<%= render 'form', military: @military %>

app/views/militaries/exemplo.html.erb
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Horizontal Form</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form class="form-horizontal">
        <div class="box-body">
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">Password</label>

                <div class="col-sm-10">
                    <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> Remember me
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-default">Cancel</button>
            <button type="submit" class="btn btn-info pull-right">Sign in</button>
        </div>
        <!-- /.box-footer -->
    </form>
</div>

app/views/militaries/index.html.erb
<h3 class="box-title">
  <%= StrHelper.model_i18n(:other, [:military])%>
  <div class="box-tools pull-right">
    <%= link_to "", new_military_path, class: 'btn btn-success btn-xs fa fa-plus', title: StrHelper.tooltip_params_i18n(:add, :military, :one), 'data-toggle' => 'tooltip', 'data-placement' => 'left' %>
  </div>  
</h3>
<div class="box">
  <!-- /.box-header -->
  <div class="box-body">
    <%= search_form_for @q, html: {class: "form-horizontal", role: "search"} do |f| %>
      <%= f.search_field :name_or_identification_or_registration_or_cpf_cont, class: "form-control", placeholder: StrHelper.system_i18n(:search, [:helpers, :layouts]) %>
    <% end %>
    <table class="table table-responsive table-hover">
      <thead>
        <tr>
          <th><%= sort_link(@q, :name, StrHelper.attribute_i18n_upper(:name, [:military])) %></th>
          <th class="col-sm-1 text-center"><%= sort_link(@q, :identification, StrHelper.attribute_i18n_upper(:identification, [:military])) %></th>
          <th class="col-sm-1 text-center"><%= sort_link(@q, :registration, StrHelper.attribute_i18n_upper(:registration, [:military])) %></th>
          <th class="col-sm-1 text-center"><%= sort_link(@q, :cpf, StrHelper.attribute_i18n_upper(:cpf,[:military])) %></th>          
          <th class="col-sm-2 text-center"><%= StrHelper.system_i18n_upper(:action, [:helpers, :layouts]) %></th>
        </tr>
      </thead>
      <tbody>
        <% @militaries.each do |military| %>
          <tr>
            <td><%= military.name %></td>
            <td align="center"><%= military.identification %></td>
            <td align="center"><%= military.registration %></td>
            <td align="center"><%= military.cpf %></td>
            <td align="center">
              <%= hidden_field(@military, military) %>
              <%= link_to("", military, class:"btn btn-default btn-xs fa fa-file-text-o", title: StrHelper.system_i18n(:show, [:helpers, :layouts]), 'data-toggle' => 'tooltip', 'data-placement' => 'left') %>
              <%= link_to("", edit_military_path(military.id), class: 'btn btn-info btn-xs fa fa-edit', title: StrHelper.system_i18n(:edit, [:helpers, :layouts]), 'data-toggle' => 'tooltip', 'data-placement' => 'left') %>
              <button type="button" class="btn btn-danger btn-xs fa " data-toggle="modal" data-target='<%="#modal-destroy-#{military.id}"%>'>
                <a class="btn-danger fa fa-trash" title="" data-toggle="tooltip" data-placement="left" href="" data-original-title='<%= StrHelper.system_i18n(:destroy, [:helpers, :layouts]) %>'></a>
              </button>
              <%= render 'helpers/modal/destroy', object_destroy: military %>            
              <button type="button" class="btn btn-success btn-xs fa" data-toggle="modal" data-target='<%="#modal-request-#{military.id}"%>'>
                <a class="btn-success fa fa-send-o" title="" data-toggle="tooltip" data-placement="left" href="" data-original-title='<%= StrHelper.system_i18n(:card_request, [:helpers, :layouts])%>'></a>
              </button>
              <%= render 'helpers/modal/card_request', object_request: military %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>
</div>

app/views/militaries/new.html.erb
<h3><%= StrHelper.system_i18n(:new, [:helpers, :layouts]) %> <%= StrHelper.model_i18n(:one, [:military])%></h3>

<%= render 'form', military: @military %>

app/views/militaries/show.html.erb
<h3><%= StrHelper.system_i18n(:show, [:helpers, :layouts]) %> <%= StrHelper.model_i18n(:one, [:military])%></h3>
<div class="box box-info">  
  <div class="form-horizontal">
    <div class="box-body">
      <div class="form-group">
        <%= label_tag( :name, StrHelper.attribute_i18n_upper(:name, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:name, @military.name, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :cpf, StrHelper.attribute_i18n_upper(:cpf, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:cpf, @military.cpf, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :identification, StrHelper.attribute_i18n_upper(:identification, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:identification, @military.identification, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag(:hierarchy, StrHelper.model_i18n_upper(:one, [:hierarchy]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:hierarchy, @military.hierarchy.name, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :father_name, StrHelper.attribute_i18n_upper(:father_name, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:father_name, @military.father_name, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :mother_name, StrHelper.attribute_i18n_upper(:mother_name, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:mother_name, @military.mother_name, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :born_date, StrHelper.attribute_i18n_upper(:born_date, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <div class="input-group date">
            <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
            </div>
            <%= text_field_tag(:born_date, @military.born_date, type:"date", class: "form-control pull-right", readonly: true)%>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :registration, StrHelper.attribute_i18n_upper(:registration, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:registration, @military.registration, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :naturalness, StrHelper.attribute_i18n_upper(:naturalness, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:naturalness, @military.naturalness, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :vote_number, StrHelper.attribute_i18n_upper(:vote_number, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:vote_number, @military.vote_number, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :vote_zone, StrHelper.attribute_i18n_upper(:vote_zone, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:vote_zone, @military.vote_zone, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :vote_section, StrHelper.attribute_i18n_upper(:vote_section, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:vote_section, @military.vote_section, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :digital_factor, StrHelper.attribute_i18n_upper(:digital_factor, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag( :digital_factor, @military.digital_factor, data:{ inputmask:'"mask": "A-9999/A-9999"', mask:""}, class: "form-control", readonly: true) %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :blood_type, StrHelper.attribute_i18n_upper(:blood_type, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:blood_type, @military.i18n_upper_blood_type, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :blood_factor, StrHelper.attribute_i18n_upper(:blood_factor, [:military]), class: 'col-sm-2 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:blood_factor, @military.i18n_upper_blood_factor, {class: "form-control", readonly: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :carry_weapon, StrHelper.attribute_i18n_upper(:carry_weapon, [:military]), class: 'col-sm-2 control-label') %>                  
        <div class="col-sm-6">
          <%= text_field_tag(:carry_weapon, MilitariesHelper.fit_carry_weapon(@military.carry_weapon), {class: "form-control", readonly: true})%>
        </div>          
      </div>
      <div class="actions">        
        <%= link_to(StrHelper.system_i18n(:back, [:helpers, :layouts]), militaries_path, class:"btn btn-default btn-sm") %>
        <div class="box-tools pull-right">
          <%= link_to(StrHelper.system_i18n(:edit, [:helpers, :layouts]), edit_military_path(@military), class:"btn btn-info btn-sm") %>
        </div>
        
      </div>
    </div>
  </div>
</div>