config/routes.rb
Rails.application.routes.draw do
  resources :discards
  resources :cards
  resources :card_requests
  resources :militaries
  resources :hierarchies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'militaries#index'

  get 'create_card_request', to: 'card_requests#create', as: :create_card_request
  get 'print_request', to: 'cards#create', as: :print_request
  get 'cancel_card_request(.:id)', to:'card_requests#cancel', as: :cancel_card_request
  patch 'giving_card', to:'cards#giving', as: :giving_card
  patch 'returning_card', to:'cards#returning', as: :returning_card

  #Print one card
  post 'print_a_card', to: 'cards#print_a_card', as: :print_a_card
  #Print 4 first cards
  get 'print_cards', to: 'cards#print_cards', as: :print_cards
  post 'create_cards', to: 'cards#create_cards', as: :create_cards

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_requests_helper.rb
# Class metodos que auxiliam CardRequest
module CardRequestsHelper
  # return Registration and Name
  def self.register_and_name(request_id)    
    card_request = CardRequest.find_by_id(request_id)
    card = Card.find_by_registration(card_request.registration)
    card.register_and_name
  end

  # Validar se solicitacao ja existe
  def self.request_exist(document, registration)
    registration = registration.gsub!(/[^0123456789]/, '')
    CardRequest.where(military_registration: registration, canceled: false).present?
  end

  def validate_card_number_by_discard(card_number)
    Discard.find_by_card_number(card_number).present?
  end
  
end

app/helpers/cards_helper.rb
# Class metodos que auxiliam CardRequest
module CardsHelper
  def self.fit_carry_weapon(fit)
    case fit
    when true
      StrHelper.system_i18n_upper(:fit, %i[helpers select])
    when false
      StrHelper.system_i18n_upper(:unfit, %i[helpers select])
    end
  end

  def self.returned_old_card(returned)
    case returned
    when true
      StrHelper.system_i18n_upper(:returned, %i[helpers select])
    when false
      StrHelper.system_i18n_upper(:unreturned, %i[helpers select])
    end
  end

  # return Registration and Name
  def self.register_name(registration)
    card = Card.find_by_registration(registration)
    card.register_and_name
  end

  # Verificacao para nova solicitacao
  def self.card_printed_exist(registration)
    Card.joins(:card_status).where(card_statuses: { describe: 'PRINTED' }).where(registration: registration).present?
  end

  # Verificacao para nova solicitacao
  def self.find_to_discard(card_request_id)
    #Card.joins(:card_status).where(card_statuses: { describe: ['PRINTED', 'USING'] }).where(card_request: card_request_id).first
    Card.find_by_card_request_id(card_request_id)
  end
  
  # Verifica numero de cedula existente
  def self.validate_card_number_by_card(card_number)
    Card.joins(:card_status).where(card_statuses: { describe: ['USING', 'RETURNED'] }).where(card_number: card_number).present?
  end

end

app/helpers/discards_helper.rb
module DiscardsHelper

    def self.validate_card_number_by_discard(card_number)
        Discard.find_by_card_number(card_number).present?
    end
    
end

app/helpers/hierarchies_helper.rb
module HierarchiesHelper
  # return Hierarchy name
  def self.hierarchy_name(id)
    hierarchy = Hierarchy.find_by_id(id)
    hierarchy.name
  end
end

app/helpers/militaries_helper.rb
module MilitariesHelper
  # return Registration and Name
  def self.hierarchy_register_and_name(registration)
    military = Military.find_by_registration(registration)
    military.hierarchy_register_and_name
  end
  # return Registration and Name
  def self.military_name(registration)
    military = Military.find_by_registration(registration)
    military.name
  end

  def self.fit_carry_weapon(fit)
    case fit
    when true
      StrHelper.system_i18n_upper(:fit, %i[helpers select])
    when false
      StrHelper.system_i18n_upper(:unfit, %i[helpers select])
    end
  end
end

app/helpers/pdfs_helper.rb
# Class manipulacao de pdfs
module PdfsHelper

    def self.gen_pdfs
        cards = CardRequest.all.select(:id).take(4)
        @pdf = CardsPdf.new(cards)
    end

end

app/helpers/str_helper.rb
# Class manipulacao de strings
module StrHelper
  # Uppercase simple strings
  def self.str_upper(str)
    str.mb_chars.upcase
  end

  # Uppercase with i18n in '...activerecord...' info messages
  def self.upper_i18n(i18n)
    I18n.t(i18n).mb_chars.upcase.to_s
  end

  # Uppercase with i18n in attributes
  def self.attribute_i18n_upper(attribute, model)
    model = %i[activerecord attributes].concat(model)
    I18n.t(attribute, scope: model).mb_chars.upcase.to_s
  end

  # Uppercase with i18n in attributes
  def self.attribute_i18n(attribute, model)
    model = %i[activerecord attributes].concat(model)
    I18n.t(attribute, scope: model).mb_chars.to_s
  end

  # Uppercase with i18n in models
  def self.model_i18n_upper(quantity, scopes)
    scopes = %i[activerecord models].concat(scopes)
    I18n.t(quantity, scope: scopes).mb_chars.upcase.to_s
  end

  # I18n in models
  def self.model_i18n(quantity, scopes)
    scopes = %i[activerecord models].concat(scopes)
    I18n.t(quantity, scope: scopes).mb_chars.to_s
  end

  # Uppercase with i18n in systems
  def self.system_i18n_upper(system, scopes)
    I18n.t(system, scope: scopes).mb_chars.upcase.to_s
  end

  # I18n for systems
  def self.system_i18n(system, scopes)
    I18n.t(system, scope: scopes).mb_chars.to_s
  end

  # I18n for tooltips with params
  def self.tooltip_params_i18n(action, model, quantity)
    scopes = %i[helpers layouts]
    parameter = model_i18n(quantity, [model])
    I18n.t(action, scope: scopes, parameter: parameter).mb_chars.to_s
  end
end

app/views/helpers/modal/_cancel_card_request.html.erb
<div class="modal fade" id='<%="modal-destroy-#{request_cancel.id}"%>' role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">                
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">
                <%= StrHelper.system_i18n(:sure_cancel, [:helpers, :submit])%>
                </h4>
            </div>                
            <div class="modal-body">
                <div class="box box-danger">
                    <div class="form-horizontal">
                        <div class="box-body">
                            <div class="form-group">
                                <%= label_tag( :military_registration, StrHelper.attribute_i18n_upper(:military_registration, [:card_request]), class: 'col-sm-5 control-label') %>
                                <div class="col-sm-6">
                                    <%= text_field_tag( :military_registration, request_cancel.military_registration, class: "form-control", readonly: true) %>
                                </div>
                            </div>
                            <div class="form-group">
                            <%= label_tag( :document_reference, StrHelper.attribute_i18n_upper(:document_reference, [:card_request]), class: 'col-sm-5 control-label') %>
                                <div class="col-sm-6">
                                    <%= text_field_tag( :document_reference, request_cancel.document_reference, class: "form-control", readonly: true) %>
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-xs pull-left" data-dismiss="modal">
                    <%= StrHelper.system_i18n(:back, [:helpers, :layouts])%>
                </button>
                <%= link_to( StrHelper.system_i18n(:confirm, [:helpers, :submit]), cancel_card_request_path(request_cancel.id), class: 'btn btn-danger btn-xs')%>
            </div>
        </div>
    </div>
</div>

app/views/helpers/modal/_card_request.html.erb
<div class="modal fade" id='<%="modal-request-#{object_request.id}"%>' role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <%= form_with(model: CardRequest.new, local: true, class: 'form-horizontal') do |form| %>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">
                        <%= StrHelper.system_i18n(:confirm_card_request, [:helpers, :submit])%>
                    </h4>
                </div>
                <div class="modal-body">
                    <div class="box box-success">
                        <div class="form-horizontal">
                            <div class="box-body">
                                <div class="form-group">
                                    <%= label_tag( :name, StrHelper.attribute_i18n_upper(:name, [:military]), class: 'col-sm-5 control-label') %>
                                    <div class="col-sm-6">
                                        <%= text_field_tag(:name, object_request.name, {class: "form-control", disabled: true})%>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <%= form.label( :military_registration, StrHelper.attribute_i18n_upper(:military_registration, [:card_request]), class: 'col-sm-5 control-label') %>
                                    <div class="col-sm-6">
                                        <%= form.text_field :military_registration, id: :card_request_military_registration, value: object_request.registration, data:{ inputmask:'"mask": "999999-9"', mask:""}, class: "form-control", readonly: true %>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <%= form.label( :document_reference, StrHelper.attribute_i18n_upper(:document_reference, [:card_request]), class: 'col-sm-5 control-label') %>
                                    <div class="col-sm-6">
                                        <%= form.text_field :document_reference, id: :card_request_document_reference, required: true, data:{ inputmask:'"mask": "BGE-999/9999"', mask:""}, class: "form-control" %>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <%= form.label( :reason_request, StrHelper.attribute_i18n_upper(:reason_request, [:card_request]), class: 'col-sm-5 control-label') %>
                                    <div class="col-sm-6">
                                        <%= form.select(:reason_request, options_for_select(CardRequest.i18n_reason_requests, :reason_request), {}, {class: "form-control"}) %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-xs pull-left" data-dismiss="modal">
                        <%= StrHelper.system_i18n(:back, [:helpers, :layouts])%>
                    </button>
                    <%= form.submit( StrHelper.system_i18n(:card_request, [:helpers, :layouts]), class: "btn btn-success btn-xs" )%>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/helpers/modal/_destroy.html.erb
<div class="modal fade" id='<%="modal-destroy-#{object_destroy.id}"%>' role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">
                  <%= StrHelper.system_i18n(:sure, [:helpers, :submit])%>
                </h4>
            </div>
            <div class="modal-body">
                <div class="box box-danger">
                    <div class="form-horizontal">
                        <div class="box-body">
                            <div class="form-group">
                                <%= label_tag( :name, StrHelper.attribute_i18n_upper(:name, [:military]), class: 'col-sm-5 control-label') %>
                                <div class="col-sm-6">
                                    <%= text_field_tag(:name, object_destroy.name, {class: "form-control", readonly: true})%>
                                </div>
                            </div>
                            <div class="form-group">
                                <%= label_tag( :registration, StrHelper.attribute_i18n_upper(:registration, [:military]), class: 'col-sm-5 control-label') %>
                                <div class="col-sm-6">
                                    <%= text_field_tag(:registration, object_destroy.registration, data:{ inputmask:'"mask": "999999-9"', mask:""}, class: "form-control", readonly: true) %>
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-xs pull-left" data-dismiss="modal">
                  <%= StrHelper.system_i18n(:back, [:helpers, :layouts])%>
                </button>
                <%= button_to(StrHelper.system_i18n(:destroy, [:helpers, :layouts]), object_destroy, method: :delete, class: 'btn btn-danger btn-xs') %>
            </div>
        </div>
    </div>
</div>

app/views/helpers/modal/_discard_card.html.erb
<div class="modal fade" id='<%="modal-discard-#{discard_card.id}"%>' role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <%= form_with(model: Discard.new, local: true, class: 'form-horizontal') do |form| %>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">
                        <%= StrHelper.system_i18n(:confirm_discard, [:helpers, :submit])%>
                    </h4>
                </div>
                <div class="modal-body">
                    <div class="box box-danger">
                        <div class="form-horizontal">
                            <div class="box-body">
                                <%= form.hidden_field(:card_request_id, id: :discard_card_request_id, value: discard_card.card_request.id) %>
                                <div class="form-group">
                                    <%= label_tag( :document_reference, StrHelper.attribute_i18n_upper(:document_reference, [:card_request]), class: 'col-sm-5 control-label') %>
                                    <div class="col-sm-6">
                                        <%= text_field_tag(:document_reference, discard_card.document_reference_request, {class: "form-control", disabled: true})%>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <%= form.label( :card_number, StrHelper.attribute_i18n_upper(:card_number, [:card]), class: 'col-sm-5 control-label') %>
                                    <div class="col-sm-6">
                                        <%= form.text_field( :card_number, id: :discard_card_number, value: discard_card.card_number, required: true, data:{ inputmask:'"mask": "9999999"', mask:""}, class: "form-control")%>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <%= form.label( :reason_discard, StrHelper.attribute_i18n_upper(:reason_discard, [:discard]), class: 'col-sm-5 control-label') %>
                                    <div class="col-sm-6">
                                        <%= form.text_area( :reason_discard, required: true, class: "form-control" )%>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-xs pull-left" data-dismiss="modal">
                        <%= StrHelper.system_i18n(:back, [:helpers, :layouts])%>
                    </button>
                    <%= form.submit( StrHelper.system_i18n(:discard, [:helpers, :layouts]), class: "btn btn-danger btn-xs" )%>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/helpers/modal/_giving_card.html.erb
<div class="modal fade" id='<%="modal-giving-#{giving_card.id}"%>' role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <%= form_for(@card = Card.find(giving_card.id), url: giving_card_path, method: :patch) do |form| %>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">
                        <%= StrHelper.system_i18n(:giving_card, [:helpers, :layouts])%>
                    </h4>
                </div>
                <div class="modal-body">
                    <div class="box box-success">
                        <div class="form-horizontal">
                            <div class="box-body">
                                <div class="form-group">
                                    <%= form.label( :name, StrHelper.attribute_i18n_upper(:name, [:card]), class: 'col-sm-5 control-label') %>
                                    <div class="col-sm-6">
                                        <%= form.text_field :name, id: :card_name, value: giving_card.name, class: "form-control", readonly: true %>                                        
                                    </div>
                                </div>
                                <div class="form-group">
                                    <%= form.label( :registration, StrHelper.attribute_i18n_upper(:registration, [:card]), class: 'col-sm-5 control-label') %>
                                    <div class="col-sm-6">
                                        <%= form.text_field(:registration, id: :card_registration, value: giving_card.registration, data:{ inputmask:'"mask": "999999-9"', mask:""}, class: "form-control", readonly: true) %>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <%= form.label( :document_reference, StrHelper.attribute_i18n_upper(:document_reference, [:card_request]), class: 'col-sm-5 control-label') %>
                                    <div class="col-sm-6">
                                        <%= form.text_field( :document_reference, id: :card_document_reference,  value: giving_card.document_reference_request, data:{ inputmask:'"mask": "BGE-999/9999"', mask:""}, class: "form-control", readonly: true )%>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <%= form.label( :card_number, StrHelper.attribute_i18n_upper(:card_number, [:card]), class: 'col-sm-5 control-label') %>
                                    <div class="col-sm-6">
                                        <%= form.text_field( :card_number, id: :card_card_number, required: true, data:{ inputmask:'"mask": "9999999"', mask:""}, class: "form-control")%>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-xs pull-left" data-dismiss="modal">
                        <%= StrHelper.system_i18n(:back, [:helpers, :layouts]) %>
                    </button>
                    <%= form.submit( StrHelper.system_i18n(:giving, [:helpers, :submit]), class: "btn btn-success btn-xs" )%>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/helpers/modal/_print_request.html.erb
<div class="modal fade" id='<%="modal-print-#{object_request.id}"%>' role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">
                    <%= StrHelper.system_i18n(:confirm_print_request, [:helpers, :submit])%>
                </h4>
            </div>
            <div class="modal-body">
                <div class="box box-success">
                    <div class="form-horizontal">
                        <div class="box-body">
                            <div class="form-group">
                                <%= label_tag( :name, StrHelper.attribute_i18n_upper(:name, [:military]), class: 'col-sm-5 control-label') %>
                                <div class="col-sm-6">
                                    <%= text_field_tag(:name, MilitariesHelper.military_name(object_request.military_registration), {class: "form-control", disabled: true})%>
                                </div>
                            </div>
                            <div class="form-group">
                                <%= label_tag( :registration, StrHelper.attribute_i18n_upper(:registration, [:military]), class: 'col-sm-5 control-label') %>
                                <div class="col-sm-6">
                                    <%= text_field_tag(:registration, object_request.military_registration, data:{ inputmask:'"mask": "999999-9"', mask:""}, class: "form-control", readonly: true) %>
                                </div>
                            </div>
                            <div class="form-group">
                                <%= label_tag( :document_reference, StrHelper.attribute_i18n_upper(:document_reference, [:card_request]), class: 'col-sm-5 control-label') %>
                                <div class="col-sm-6">
                                    <%= text_field_tag( :document_reference, object_request.document_reference, data:{ inputmask:'"mask": "BGE-999/9999"', mask:""}, class: "form-control", readonly: true) %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-xs pull-left" data-dismiss="modal">
                    <%= I18n.t 'helpers.layouts.back'%>
                </button>                
                <%= link_to(StrHelper.system_i18n(:print, [:helpers, :submit]), new_card_path(object_request_id: object_request.id), class:"btn btn-success btn-xs") %>
            </div>
        </div>
    </div>
</div>

app/views/helpers/modal/_return_card.html.erb
<div class="modal fade" id='<%="modal-return-#{return_card.id}"%>' role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">
                  <%= StrHelper.system_i18n(:sure, [:helpers, :submit])%>
                </h4>
            </div>
            <div class="modal-body">
                <div class="box box-danger">
                    <div class="form-horizontal">
                        <div class="box-body">
                            <div class="form-group">
                                <%= label_tag( :name, StrHelper.attribute_i18n_upper(:name, [:military]), class: 'col-sm-5 control-label') %>
                                <div class="col-sm-6">
                                    <%= text_field_tag(:name, return_card.name, {class: "form-control", readonly: true})%>
                                </div>
                            </div>
                            <div class="form-group">
                                <%= label_tag( :registration, StrHelper.attribute_i18n_upper(:registration, [:military]), class: 'col-sm-5 control-label') %>
                                <div class="col-sm-6">
                                    <%= text_field_tag(:registration, return_card.registration, data:{ inputmask:'"mask": "999999-9"', mask:""}, class: "form-control", readonly: true) %>
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-xs pull-left" data-dismiss="modal">
                  <%= StrHelper.system_i18n(:back, [:helpers, :layouts])%>
                </button>
                <%= button_to(StrHelper.system_i18n(:return, [:helpers, :layouts]), return_card, method: :delete, class: 'btn btn-danger btn-xs') %>
            </div>
        </div>
    </div>
</div>