config/routes.rb
Rails.application.routes.draw do
  resources :discards
  resources :cards
  resources :card_requests
  resources :militaries
  resources :hierarchies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'militaries#index'

  get 'create_card_request', to: 'card_requests#create', as: :create_card_request
  get 'print_request', to: 'cards#create', as: :print_request
  get 'cancel_card_request(.:id)', to:'card_requests#cancel', as: :cancel_card_request
  patch 'giving_card', to:'cards#giving', as: :giving_card
  patch 'returning_card', to:'cards#returning', as: :returning_card

  #Print one card
  post 'print_a_card', to: 'cards#print_a_card', as: :print_a_card
  #Print 4 first cards
  get 'print_cards', to: 'cards#print_cards', as: :print_cards
  post 'create_cards', to: 'cards#create_cards', as: :create_cards

end

app/models/card_request.rb
# Classe responsavel por representar Solicitacoes de carteiras
class CardRequest < ApplicationRecord
  before_validation :clean_mask

  has_one :card

  validates :military_registration, presence: true, length: { is: 7 }
  validates :document_reference, presence: true
  validates :reason_request, presence: true

  enum reason_request: { change_data: 1, include: 2, promotion: 3, unuseble: 4, reinclude: 5, expired: 6, tired: 7 }

  def clean_mask
    military_registration.gsub!(/[^0123456789]/, '')
  end

  # Formatacao de data para exibicao
  def date_formatted
    created_at.strftime('%d/%m/%Y') if created_at?
  end

  def register_and_document
    "#{military_registration} - #{document_reference}"
  end

  # Internationalization (I18n)
  # reason_request: Internationalization (I18n)
  def i18n_reason_request
    StrHelper.attribute_i18n(reason_request.to_sym, %i[card_request reason_requests])
  end

  # reason_request: Internationalization (I18n) with uppercase
  def i18n_upper_reason_request
    StrHelper.attribute_i18n_upper(reason_request.to_sym, %i[card_request reason_requests])
  end

  # Hash reason_requests: Internationalization (I18n)
  def self.i18n_reason_requests(hash = {})
    reason_requests.each_key do |key|
      hash[StrHelper.attribute_i18n(key.to_sym, %i[card_request reason_requests])] = key
    end
    hash
  end

  # Hash reason_requests: Internationalization (I18n) with uppercase
  def self.i18n_upper_reason_requests(hash = {})
    reason_requests.each_key do |key|
      hash[StrHelper.attribute_i18n_upper(key.to_sym, %i[card_request reason_requests])] = key
    end
    hash
  end
end

app/controllers/card_requests_controller.rb
# CardRequestsController controla link com view
class CardRequestsController < ApplicationController
  before_action :set_card_request, only: %i[show edit update destroy]

  # GET /card_requests
  # GET /card_requests.json
  def index
    collection = CardRequest.joins("LEFT JOIN cards ON card_requests.id = cards.card_request_id").where(cards: {card_request_id: nil}).where(card_requests: {canceled: false})
    @q = collection.ransack(params[:q])
    @card_requests = @q.result(distinct: true).order(created_at: :desc)
    
  end
  # GET /card_requests/1
  # GET /card_requests/1.json
  def show; end

  # GET /card_requests/new
  def new
    @card_request = CardRequest.new
  end

  # GET /card_requests/1/edit
  def edit; end

  # POST /card_requests
  # POST /card_requests.json
  def create
    @card_request = CardRequest.new(card_request_params)    
    if CardsHelper.card_printed_exist(@card_request.military_registration)
      redirect_to militaries_url, flash: { error: StrHelper.system_i18n_upper(:card_printed_exist, %i[errors messages]) }
    elsif CardRequestsHelper.request_exist(@card_request.document_reference, @card_request.military_registration)
      redirect_to militaries_url, flash: { error: StrHelper.system_i18n_upper(:request_exist, %i[errors messages]) }
    elsif @card_request.save
      redirect_to card_requests_url, flash: { success: StrHelper.system_i18n_upper(:create, %i[activerecord success]) }
    else
      flash.now[:error] = @card_request.errors.full_messages.first
      redirect_to militaries_url, flash: { error: @card_request.errors.full_messages.first }
    end
  end

  # PATCH/PUT /card_requests/1
  # PATCH/PUT /card_requests/1.json
  def update
    if @card_request.update(card_request_params)
      redirect_to @card_request, flash: { success: StrHelper.system_i18n_upper(:update, %i[activerecord success]) }
    else
      flash.now[:error] = @card_request.errors.full_messages.first
      render :edit
    end
  end

  # DELETE /card_requests/1
  # DELETE /card_requests/1.json
  def destroy
    if @card_request.destroy
      redirect_to card_requests_url, flash: { success: StrHelper.system_i18n_upper(:destroy, %i[activerecord success]) }
    else
      redirect_to card_requests_url, flash: { error: @card_request.errors.full_messages.first }
    end
  end

  # CANCEL /card_requests/1
  # CANCEL /card_requests/1.json
  def cancel
    card_request = CardRequest.find_by_id(params[:id])
    card_request.canceled = true
    if card_request.save
      redirect_to card_requests_url, flash: { success: StrHelper.system_i18n_upper(:cancel, %i[activerecord success]) }
    else
      redirect_to card_requests_url, flash: { error: card_request.errors.full_messages.first }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_card_request
    @card_request = CardRequest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def card_request_params
    params.require(:card_request).permit(:military_registration, :document_reference, :reason_request, :canceled)
  end
end

app/helpers/card_requests_helper.rb
# Class metodos que auxiliam CardRequest
module CardRequestsHelper
  # return Registration and Name
  def self.register_and_name(request_id)    
    card_request = CardRequest.find_by_id(request_id)
    card = Card.find_by_registration(card_request.registration)
    card.register_and_name
  end

  # Validar se solicitacao ja existe
  def self.request_exist(document, registration)
    registration = registration.gsub!(/[^0123456789]/, '')
    CardRequest.where(military_registration: registration, canceled: false).present?
  end

  def validate_card_number_by_discard(card_number)
    Discard.find_by_card_number(card_number).present?
  end
  
end

app/views/card_requests/_form.html.erb
<div class="box box-info">
  <%= form_with(model: card_request, local: true, class: 'form-horizontal') do |form| %>
    <div class="box-body">
      <div class="form-group">
        <%= form.label( :military_registration, StrHelper.attribute_i18n_upper(:military_registration, [:card_request]), class: 'col-sm-3 control-label') %>
        <div class="col-sm-6">
          <%= form.text_field :military_registration, id: :card_request_military_registration, class: "form-control", readonly: true %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label( :document_reference, StrHelper.attribute_i18n_upper(:document_reference, [:card_request]), class: 'col-sm-3 control-label') %>
        <div class="col-sm-6">
          <%= form.text_field :document_reference, id: :card_request_document_reference, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label( :reason_request, StrHelper.attribute_i18n_upper(:reason_request, [:card_request]), class: 'col-sm-3 control-label') %>
          <div class="col-sm-6">
            <%= form.select(:reason_request, options_for_select(CardRequest.i18n_reason_requests, @card_request.reason_request), {}, {class: "form-control"}) %>
          </div>
      </div>
      <div class="actions">
        <%= link_to(StrHelper.system_i18n(:back, [:helpers, :layouts]), card_requests_path, class:"btn btn-default btn-sm") %>
        <div class="box-tools pull-right">
          <%= form.submit( StrHelper.system_i18n(:save, [:helpers, :layouts]), class:"btn btn-success btn-sm" )%>
        </div>
      </div>
    </div>    
  <% end %>
</div>

app/views/card_requests/edit.html.erb
<h3><%= StrHelper.system_i18n(:edit, [:helpers, :layouts]) %> <%= StrHelper.model_i18n(:one, [:card_request])%></h3>

<%= render 'form', card_request: @card_request %>

app/views/card_requests/index.html.erb
<h3>
  <%= StrHelper.model_i18n(:other, [:card_request])%>
  <div class="box-tools pull-right">
    <%= link_to("", print_cards_path, class: 'btn btn-success btn-xs fa fa-print', title: StrHelper.tooltip_params_i18n(:print_4, :card, :other), 'data-toggle' => 'tooltip', 'data-placement' => 'left') %>
  </div>
</h3>
<p id="notice">
  <%= notice %>
</p>
<div class="box">
  <div class="box-body">
    <%= search_form_for @q, html: {class: "form-horizontal", role: "search"} do |f| %>
      <%= f.search_field :military_registration_or_document_reference_cont, class: "form-control", placeholder: StrHelper.system_i18n(:search, [:helpers, :layouts]) %>
    <% end %>
    <table class="table table-responsive table-hover">
      <thead>
        <tr>
          <th class="col-sm-3 text-center"><%= sort_link(@q, :military_registration, StrHelper.attribute_i18n_upper(:military_registration, [:card_request])) %></th>
          <th class="col-sm-3 text-center"><%= sort_link(@q, :document_reference, StrHelper.attribute_i18n_upper(:document_reference, [:card_request])) %></th>
          <th class="col-sm-3 text-center"><%= sort_link(@q, :created_at, StrHelper.attribute_i18n_upper(:date_request, [:card_request])) %></th>          
          <th class="col-sm-3 text-center"><%= StrHelper.system_i18n_upper(:action, [:helpers, :layouts]) %></th>
        </tr>
      </thead>
      <tbody>
        <% @card_requests.each do |card_request| %>
          <tr>
            <td align="center">
              <%= card_request.military_registration %>
            </td>
            <td align="center">
              <%= card_request.document_reference %>
            </td>
            <td align="center">
              <%= card_request.date_formatted %>
            </td>
            <td align="center">
              <%= hidden_field(@card_request, card_request) %>
              <%= link_to( "", edit_card_request_path(card_request.id), class: 'btn btn-info btn-xs fa fa-edit', title: StrHelper.system_i18n(:edit, [:helpers, :layouts]), 'data-toggle' => 'tooltip', 'data-placement' => 'left')%>
              <button type="button" class="btn btn-danger btn-xs fa " data-toggle="modal" data-target='<%="#modal-destroy-#{card_request.id}"%>'>
                  <a class="btn-danger fa fa-ban" title="" data-toggle="tooltip" data-placement="left" href="" data-original-title='<%= StrHelper.system_i18n(:cancel, [:helpers, :layouts]) %>'></a>
                </button>
                <%= render 'helpers/modal/cancel_card_request', request_cancel: card_request %>            
              <button type="button" class="btn btn-success btn-xs fa" data-toggle="modal" data-target='<%="#modal-print-#{card_request.id}"%>'>
                <a class="btn-success fa fa-print" title="" data-toggle="tooltip" data-placement="left" href="" data-original-title='<%= StrHelper.system_i18n(:print_request, [:helpers, :layouts])%>'></a>
              </button>
              <%= render 'helpers/modal/print_request', object_request: card_request %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/card_requests/new.html.erb
<h3><%= StrHelper.system_i18n(:new, [:helpers, :layouts]) %> <%= StrHelper.model_i18n(:one, [:card_request])%></h3>

<%= render 'form', card_request: @card_request %>

app/views/card_requests/show.html.erb
<h3><%= StrHelper.system_i18n(:show, [:helpers, :layouts]) %> <%= StrHelper.model_i18n(:one, [:card_request])%></h3>
<div class="box box-info">  
  <div class="form-horizontal">
    <div class="box-body">
      <div class="form-group">
        <%= label_tag( :military_registration, StrHelper.attribute_i18n_upper(:military_registration, [:card_request]), class: 'col-sm-3 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:military_registration, @card_request.military_registration, {class: "form-control", disabled: true})%>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :document_reference, StrHelper.attribute_i18n_upper(:document_reference, [:card_request]), class: 'col-sm-3 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag( :document_reference, @card_request.document_reference, {class: "form-control", disabled: true}) %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag( :reason_request, StrHelper.attribute_i18n_upper(:reason_request, [:card_request]),class: 'col-sm-3 control-label') %>
        <div class="col-sm-6">
          <%= text_field_tag(:reason_request, @card_request.i18n_reason_request, {class: "form-control", disabled: true})%>
        </div>
      </div>
      <div class="actions">        
        <%= link_to(StrHelper.system_i18n(:back, [:helpers, :layouts]), card_requests_path, class:"btn btn-default btn-sm") %>
        <div class="box-tools pull-right">
            <%= link_to(StrHelper.system_i18n(:edit, [:helpers, :layouts]), edit_card_request_path(@card_request), class:"btn btn-info btn-sm") %>
        </div>                
      </div>
    </div>
  </div>
</div>

app/views/card_requests/to_list.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h1 class="page-header"><%= I18n.t 'buttons.list_militaries' %></h1>
    <div class="col-md-12">
      <%= form_tag(militaries_listed_path, method: :get) do %>
          <%= select_tag(:registration_list, options_from_collection_for_select(@users, :registration, :register_and_name), :multiple => true, :class => "searchable") %>
          <div style="float: right">
            <%= submit_tag "Listar", class: "form_submit btn btn-default" %>
          </div>
      <% end %>
    </div>
  </div>
</div>